# Generated by Django 6.1.1 on 2026-10-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New conversation', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('diagnosed', 'Diagnosed'), ('booked', 'Booked'), ('closed', 'Closed')], default='active', max_length=20)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('vehicle_make', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('likely_issue', models.CharField(max_length=200)),
                ('reasoning', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('can_drive', models.BooleanField(default=False)),
                ('next_step', models.TextField()),
                ('recommended_service', models.CharField(max_length=200)),
                ('generated_by', models.CharField(choices=[('rule_engine', 'Rule Engine'), ('gemini', 'Gemini')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='chatbot.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('generated_by', models.CharField(choices=[('user', 'User'), ('rule_engine', 'Rule Engine'), ('gemini', 'Gemini')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to='chatbot.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to='chatbot.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
